#ifndef BUILDMANAGER_GLOBAL_H
#define BUILDMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUILDMANAGER_LIBRARY)
#  define BUILDMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BUILDMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BUILDMANAGER_GLOBAL_H
