#ifndef PROJECTMANAGER_GLOBAL_H
#define PROJECTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROJECTMANAGER_LIBRARY)
#  define PROJECTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROJECTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJECTMANAGER_GLOBAL_H
